name: Build & Deploy Pipeline

on:
  push:
    paths:
      - "kubetask/**"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get short Git commit SHA
      id: vars
      run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${TAG} ./kubetask
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${TAG}

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/argo-app:${TAG}|" kubernetes/deployment.yml

    - name: Setup Git
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER }}"

    - name: Commit and push manifest changes
      run: |
        git add kubernetes/deployment.yml
        git commit -m "Update image tag to ${TAG}"
        git push origin main
